site_name: AI集群官方文档

# Repository
repo_name: 'piaozhx/DockerMonitor'
repo_url: 'https://github.com/piaozhx/DockerMonitor'

nav:
    - Home: index.md
    - Start: start.md
    - QA:
      - '集群管理相关': 'QA_cluster.md'
      - 'Linux基础知识': 'QA_linux.md'
      - '容器配置相关': 'QA_container.md'
    - 道德准则: moral.md
    - About: about.md

theme:
  name: material
  highlightjs: true
  hljs_languages:
      - yaml
      - rust
      - bash
  palette:
    primary: 'teal'
    accent: 'red'


dev_addr: 0.0.0.0:8898


markdown_extensions:
  - codehilite:
      linenums: true
  - toc:
      permalink: true

extra:
    version: 1.0